In [1]:
#importar as bibliotecas
import numpy as np

In [2]:
print('Versão atual do numpy é:', np.__version__)

Versão atual do numpy é: 1.18.5


In [3]:
a = np.arange(15)
print('O vetor de arange e',a)

O vetor de arange e [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [4]:
#reshape transformar meu vetor em uma matriz
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
#Mostrar o formato da minha matriz
a.shape

(3, 5)

In [6]:
#Mostrar quantas dimensões tem minha matriz
a.ndim

2

In [7]:
#Mostrar o tipo de dado
a.dtype.name

'int32'

In [8]:
#Mostrar o tamanho em bytes do tipo de arquivo
a.itemsize

4

In [9]:
#Mostrar o tamanho da minha matriz
a.size

15

In [10]:
#Mostrar o tipo de dado
type(a)

numpy.ndarray

In [11]:
#Criar um array 
b = np.array([6, 7, 8, 4])
b

array([6, 7, 8, 4])

In [12]:
b = np.array([6, 7, 8, 4]).reshape(2,2)
b

array([[6, 7],
       [8, 4]])

In [14]:
#Mostrar as dimensões 
b.ndim

2

In [15]:
#Mostrar tipo de dado
type(b)

numpy.ndarray